baseURL      = 'https://odaisomoto.github.io'
languageCode = 'en-us'
title        = 'Fery Prasetia | Creative Manager Resume & Portfolios'


[params]
  description = "Fery Prasetia, Creative Manager, Video Editor, Video Production, Project Manager. Personal website for Resume & Portfolios"
  keywords    = "Fery Prasetia, personal website, portfolio, resume, cv"

  [params.author]
    name = 'Fery Prasetia'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
